Rego azure ia c
prancer-io/prancer-compliance-test pull request #132
Opened 2021-07-13 03:59 UTC by shahinshirvani

2021-07-14 22:44 UTC, farchide requested changes

2021-07-18 07:26 UTC, shahinshirvani commented on azure/iac/KeyVault.rego
> +    "Policy Title": "ENSURE THE KEY VAULT IS RECOVERABLE - ENABLE 'SOFT DELETE' SETTING FOR A KEY VAULT",
I fixed that

2021-07-18 07:27 UTC, shahinshirvani commented on azure/iac/LogProfile.rego
> +    count(resource.properties.locations) < 65
I fixed that

2021-07-18 07:44 UTC, shahinshirvani commented on azure/iac/KeyVault.rego
> +    "Policy Title": "ENSURE THAT KEYVAULT IS IN USE",
I fixed that

2021-07-19 06:28 UTC, rezoan commented on azure/iac/KeyVault.rego
> +    accessPolicie := resource.properties.accessPolicies[_]
accessPolicie should be accessPolicy

2021-07-21 21:46 UTC, closed without merging

2021-07-22 03:39 UTC, rezoan commented
@farchide @shahinshirvani any reason to close this PR without fixing all the issues mentioned in the review?