Azure iac new rego files (web.rego, sql_servers_auditing.rego , securitycontacts.rego)
prancer-io/prancer-compliance-test pull request #214
Opened 2021-08-23 14:42 UTC by shahinshirvani

2021-08-23 20:00 UTC, farchide requested changes

2021-08-24 03:54 UTC, shahinshirvani commented on azure/iac/web.rego
> +    "Policy Title": "Azure App Service Web app should redirects HTTP to HTTPS",
fixed

2021-08-24 04:10 UTC, shahinshirvani commented on azure/iac/sql_servers_auditing.rego
> +    lower(resource.type) == "microsoft.sql/servers/auditingsettings"
I created a separate rule for that when ```auditingsettings```is a sub resource of ```microsoft.sql/servers```

2021-08-24 22:37 UTC, farchide approved these changes

2021-08-24 22:37 UTC, merged