add secrets.rego and add in master-compliance-test
prancer-io/prancer-compliance-test pull request #67
Opened 2021-03-07 11:56 UTC by shahinshirvani

2021-03-10 05:37 UTC, farchide requested changes
@shahinshirvani update the title and description with the items provided

2021-03-10 05:37 UTC, farchide commented on aws/iac/master-compliance-test.json
> +                    "title": "",
title: `Secrets should be removed from the source code`

2021-03-10 05:37 UTC, farchide commented on aws/iac/master-compliance-test.json
> +                    "description": "",
Description: `We should not have any secret in the source code. Make sure to put the secrets in a vault`

2021-03-10 05:48 UTC, shahinshirvani commented
i updated those info

2021-03-15 05:14 UTC, farchide approved these changes

2021-03-15 05:14 UTC, merged