add master-compliance-test and master-snapshot for K8S-iac
prancer-io/prancer-compliance-test pull request #68
Opened 2021-03-09 05:20 UTC by shahinshirvani

2021-03-10 05:43 UTC, farchide requested changes
@shahinshirvani file structure is not correct

2021-03-10 05:43 UTC, farchide commented on kubernetes/iac/master-compliance-test.json
> +                            "compliance": ["CIS 140"],
@shahinshirvani change all `CIS 140` to `CIS`

2021-03-10 05:43 UTC, farchide commented on kubernetes/iac/master-compliance-test.json
> +{
@shahinshirvani file structure is not correct. there should be one master test name, one cases and all tests should be under cases

2021-03-10 06:08 UTC, shahinshirvani commented
i fixed these issues about change tag and structure

2021-03-15 05:15 UTC, farchide approved these changes

2021-03-15 05:16 UTC, merged